# inspired by: https://github.com/golangci/golangci-lint/blob/master/.golangci.yml

run:
  go: "1.22"

linters-settings:
  revive:
    rules:
      # Disable var-naming for package name - Yaegi requires underscores
      # when module path contains hyphens (traefik-geoblock-asn -> traefik_geoblock_asn)
      - name: var-naming
        disabled: true
  stylecheck:
    # Disable ST1003 (underscores in package names) - Yaegi requires underscores
    checks: ["all", "-ST1003"]
  # dupl:
  #   threshold: 100
  funlen:
    lines: 100
    statements: 50
  lll:
    line-length: 125
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - asciicheck
    # - bidichk
    # - bodyclose
    # - contextcheck
    # - depguard
    - dogsled
    # - dupl
    # - durationcheck
    - errcheck
    # - errname
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    # - nilnil
    # - noctx
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    # - tagliatelle
    # - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

    # don't enable:
    # - prealloc
